tg_token: "8105869618:AAHWyL94ronqJY4KuNeq9105eZngOQFaCgo"
use_chatgpt_api: true
chatgpt_model: "gpt-4"
enable_message_streaming: false
allowed_telegram_usernames:
  - NikitaEgozha
  - Fit_curly
new_dialog_timeout: 600
use_mongo: true
mongodb_uri: "mongodb+srv://negozha:vl3QKOOjhGNcYrU7@cluster0.8tltm2s.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
