tg_token: "8105869618:AAHWyL94ronqJY4KuNeq9105eZngOQFaCgo"
openai_api_key: "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"
use_chatgpt_api: true
chatgpt_model: "gpt-4"
enable_message_streaming: false
allowed_telegram_usernames:
  - NikitaEgozha
  - Fit_curly
new_dialog_timeout: 600
use_mongo: true
